slurmImage: ghcr.io/stackhpc/slurm-docker-cluster:1f51003

login:
  # Deployment resource name
  name: login
  replicas: 1

slurmd:
  # StatefulSet resource name
  name: slurmd # NB this must match NodeName= in slurm-cluster-chart/files/slurm.conf
  replicas: 2

slurmctld:
  # StatefulSet resource name
  name: slurmctld
  # NOTE: We don't include a replicas field here because
  # replicas > 1 for slurmctld needs extra Slurm config

storage:
  mountPath: /home
  # The name of a Read-Write-Many StorageClass to use for
  # the persistent volume which is shared across Slurm nodes
  # Note: If using the default value then you must set
  # rooknfs.enabled = true below to ensure that Rook NFS is 
  # installed on the cluster as a dependency of this Slurm
  # chart. If you are using a separate RWM StorageClass, then
  # set rooknfs.enabled = false
  storageClassName: longhorn
  # Name for the R-W-M volume to provision
  claimName: slurm-shared-storage
  # Capacite of the R-W-M volume
  capacity: &capacity 10Gi   # NB yaml anchor used so this value is also set for `rooknfs.storageCapacity` if necessary.

# Values for Slurm's database container
database:
  #Database image to be used
  image: mariadb:10.10
  #Storage requested by the var-lib-mysql volume backing the database
  storage: 100Mi

# Configmap resource names
configmaps:
  slurmConf: slurm-conf-configmap
  slurmdbdConf: slurmdbd-conf-configmap
  sshdConfig: sshd-config-configmap

# Public key used for ssh access to the login node
# If let undefined, assumes you have run the provided publish-keys.sh script to publish your public key prior to deployment
sshPublicKey:

# Secret resource names
secrets:
  mungeKey: munge-key-secret

openOnDemand:
  #Password for default Open OnDemand user 'rocky'
  password: password
